pos_file: "data/raw/mean_md-pos-1.xyz"
frc_file: "data/raw/mean_md-frc-1.xyz"
temperature: 300.0
temperature_target: 300
temperature_target_surface: 450
max_displacement: 2.0
max_random_displacement: 0.1
surface_atom_types:
 - "Cs"
 - "Br"
clustering_method: "KMeans"
num_clusters: 100  
num_samples_pca: 1200  
num_samples_pca_surface: 600
num_samples_randomization: 200
