run: [train, val, test]


cutoff_radius: 12.0
model_type_names: [Cd, Cl, Se] 
chemical_species: ${model_type_names}

data:
  _target_: nequip.data.datamodule.ASEDataModule
  seed: 456             
  split_dataset:
    file_path:  #./consolidated_dataset_1000_CdSe_new.xyz
    train: 0.8
    val: 0.1
    test: 0.1
  transforms:
    - _target_: nequip.data.transforms.NeighborListTransform
      r_max: ${cutoff_radius}
    - _target_: nequip.data.transforms.ChemicalSpeciesToAtomTypeMapper
      model_type_names: ${model_type_names}
  
  train_dataloader:
    _target_: torch.utils.data.DataLoader
    batch_size: 16
  val_dataloader:
    _target_: torch.utils.data.DataLoader
    batch_size: 16
  test_dataloader: ${data.val_dataloader}
  stats_manager:
    _target_: nequip.data.CommonDataStatisticsManager
    type_names: ${model_type_names}

trainer:
  _target_: lightning.Trainer
  accelerator: auto
  devices: 1    # NO of GPUs
  max_epochs: 3
  check_val_every_n_epoch: 1
  log_every_n_steps: 5
  
  callbacks:
      
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      dirpath: ./results 
      filename: best
      save_last: true
    
    - _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: val0_epoch/weighted_sum        # validation metric to monitor
      min_delta: 1e-3                         # how much to be considered a "change"
      patience: 20                            # how many instances of "no change" before stopping
      
  logger:
    - _target_: lightning.pytorch.loggers.TensorBoardLogger
      save_dir: ./logs
      name: tutorial_log
      version: null
      default_hp_metric: false


# NOTE:
# interpolation parameters for Allegro model
num_scalar_features: 64


training_module:
  _target_: nequip.train.EMALightningModule
  
  loss:
    _target_: nequip.train.EnergyForceLoss
    per_atom_energy: true
    coeffs:
      total_energy: 0.05
      forces: 0.95
      
  val_metrics:
    _target_: nequip.train.EnergyForceMetrics
    coeffs:
      per_atom_energy_mae: 0.05
      forces_mae: 0.95
      
  train_metrics: ${training_module.val_metrics}
  test_metrics: ${training_module.val_metrics}
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.001

  model:
    _target_: allegro.model.AllegroModel
    
    #compile_mode: compile
    
    seed: 456
    model_dtype: float32
    type_names: ${model_type_names}
    r_max: ${cutoff_radius}


    radial_chemical_embed:
      _target_: allegro.nn.TwoBodyBesselScalarEmbed
      num_bessels: 8
      bessel_trainable: false
      polynomial_cutoff_p: 6

    radial_chemical_embed_dim: ${num_scalar_features}

    # scalar embedding MLP
    scalar_embed_mlp_hidden_layers_depth: 1
    scalar_embed_mlp_hidden_layers_width: ${num_scalar_features}
    scalar_embed_mlp_nonlinearity: silu

    l_max: 1

    num_layers: 2

    num_scalar_features: ${num_scalar_features}

    num_tensor_features: 32

    allegro_mlp_hidden_layers_depth: 1
    allegro_mlp_hidden_layers_width: ${num_scalar_features}
    allegro_mlp_nonlinearity: silu

    parity: true

    tp_path_channel_coupling: true

    readout_mlp_hidden_layers_depth: 1
    readout_mlp_hidden_layers_width: ${num_scalar_features}
    readout_mlp_nonlinearity: silu

    avg_num_neighbors: ${training_data_stats:num_neighbors_mean}

    # per-type per-atom scales and shifts
    per_type_energy_shifts: ${training_data_stats:per_atom_energy_mean}

    per_type_energy_scales: ${training_data_stats:forces_rms}
    per_type_energy_scales_trainable: false
    per_type_energy_shifts_trainable: false


    pair_potential:
      _target_: nequip.nn.pair_potential.ZBL
      units: real     # Ang and kcal/mol, LAMMPS unit names;  allowed values "metal" and "real"
      chemical_species: ${chemical_species}   # must tell ZBL the chemical species of the various model atom types
