# Example of an unified file with the common parameters used by all
# the engines employed by the MLFF_QD platform.

platform: fusion  # (schnet, painn, fusion, nequip, allegro, mace)
common:
  data:
    input_xyz_file: ./basic_consolidated_dataset_1000CdSe.xyz

  model:
    layers: 3
    features: 32
    cutoff: 12.0
    n_rbf: 20
    l_max: 1
    parity: true
    model_dtype: float32
    chemical_symbols: [Cd, Se, Cl]
    
  training:
    seed: 42
    train_size: 0.8
    val_size: 0.1
    test_size: 0.1
    batch_size: 16
    epochs: 3
    learning_rate: 0.001
    num_workers: 24
    device: cuda
    log_every_n_steps: 5
    optimizer: AdamW
    scheduler:
      type: ReduceLROnPlateau
      factor: 0.8
      patience: 5
    pin_memory: true
    
  loss:
    energy_weight: 0.05
    forces_weight: 0.95
    
  output:
    output_dir: ./resultsNewNewX
    

