dataset:
   input_file: "dataset_pos_frc_ev.xyz"
   output_prefix: "consolidated_dataset" 
   sizes: [200,500,1000]
  # Subset counts (number of structures from each method)
   subset_counts:
     MD: 4036  # Structures obtained from Molecular Dynamics (MD) simulation 
   contamination: 0.05 # Fraction of outliers removed by Isolation Forest 
SOAP: 
   species: ["In", "P", "Cl"] 
   r_cut: 12.0 
   n_max: 7 
   l_max: 3 
   sigma: 0.1 
   periodic: False
   sparse: False