platform: painn  # Options: allegro, mace, nequip, schnet, painn, fusion

common:
  input_xyz_file: ./basic_consolidated_dataset_1000CdSe.xyz
  seed: 42
  train_size: 0.7  # 800 or 0.8
  val_size: 0.3
  batch_size: 16
  epochs: 3
  output_dir: ./results
  chemical_symbols: [Cd, Se, Cl]
  learning_rate: 0.001
  energy_loss_weight: 0.05
  forces_loss_weight: 0.95
  num_workers: 24
  device: cuda
  log_every_n_steps: 10
  #n_rbf: 20  # Optional, used by SchNet/Painn/Fusion

overrides:
  schnet:
    cutoff: 12.0
    layers: 2
    features: 192

  painn:
    cutoff: 12.0
    layers: 2
    features: 192

  fusion:
    cutoff: 12.0
    layers: 2
    features: 192
    l_max: 1

  nequip:
    cutoff: 12.0
    layers: 3
    features: 32

  allegro:
    cutoff: 12.0
    layers: 2
    features: 64

  mace:
    cutoff: 12.0
    layers: 3
    features: 64
