# config.yaml
model_path: "../models_painn/best_inference_cspbbr3_model_1"
cutoff: 12.0
skin: 2.0 
prefactor: 14.39964
log_file: "simulation.log"
cache_path: "neighbor_cache"
include_electrostatic: False 
initial_xyz: "../CsPbBr3.xyz"

run_type: "GEO_OPT"  # Change to "GEO_OPT" for geometry optimization

eval:
  batch_size: 16  
  uncertainty: ["ensemble"]  
  training_data: "../consolidated_dataset_100.xyz"  # Replace with actual path
  eval_input_xyz: "../consolidated_dataset_150.xyz"
  eval_output_file: "output.xyz"
  eval_log_file: "eval_log.txt"
#  unlabeled_pool_path: "md_trajectory.xyz"
  error_estimate: False 
  plot: False  
  ensemble_folder: "../models_painn"
  ensemble_size: 10 
  test_ensemble: False
  active_learning: "influence"  
#  plot_smooth_window: 50     # (optional) window for the rolling‐mean plot
  pool_stride:       1      # thin the pool by this many frames
  pool_window:       200     # frames per AL window
#  pool_max_per_window: 5     # max picks per window
  SOAP:
    species: ["Cd", "Se", "Cl"]
    r_cut: 12.0
    n_max: 7
    l_max: 3
    sigma: 0.1
    periodic: False
    sparse: False

md:
  timestep_fs: 1.0
  temperature_K: 300.0
  trajectory_file_md: "md_trajectory.xyz"
  log_file: "simulation_md.log" 
  use_langevin: true
  friction_coefficient: 0.01
  steps: 25000  
  xyz_print_interval: 5  

geo_opt:
  geo_opt_fmax: 0.02
  geo_opt_steps: 500
  trajectory_file_geo_opt: "geo_opt_trajectory.xyz"

vib:
  vib_opt_fmax: 0.001
  vib_opt_steps: 1000
  trajectory_file_vib: "vib_trajectory.xyz"
  log_file_vib: "vib_opt.log"
  vib_output_file: "vibrational_frequencies.txt"
  vdos_plot_file: "vdos_plot.png"
  delta: 10 


