# ───────────────────────────────────────────────
#                 Dataset Input
#  Choose ONE of the two options below for your data.
# ───────────────────────────────────────────────
dataset:
  # --- Option A: Use a single, pre-combined file (Recommended) ---
  # Uncomment 'input_file' if you have one file with positions, forces, and energy.
  # input_file: "dataset_pos_frc_ev.xyz"

  # --- Option B: Auto combine separate position and force files ---
  # Use these lines if your positions and forces are in two different files.
   pos_file: "HgTe-pos-1.xyz"
   frc_file: "HgTe-frc-1.xyz"
  
   output_prefix: "consolidated_dataset" 
   
   sizes: [200,500]
  # Subset counts (number of structures from each method)
   subset_counts:
     MD: 4036  # Structures obtained from Molecular Dynamics (MD) simulation 
   contamination: 0.05 # Fraction of outliers removed by Isolation Forest 
   
# ───────────────────────────────────────────────
# Optional SOAP descriptor settings
# (You can safely remove this section to let MLFF-QD
#  auto-detect species and use default SOAP parameters)
# ───────────────────────────────────────────────
SOAP: 
   species: ["Hg", "Cl", "Te"] 
   r_cut: 12.0 
   n_max: 7 
   l_max: 3 
   sigma: 0.1 
   periodic: False
   sparse: False